services:
  - type: web
    name: mytragor-simulador
    env: node
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1